# Generated by Django 3.1.2 on 2020-10-29 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidad',
            options={'verbose_name_plural': 'Especialidades'},
        ),
    ]
