# Generated by Django 3.1.2 on 2020-11-03 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialidad', '0002_auto_20201103_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidad',
            options={'verbose_name_plural': 'especialidades'},
        ),
    ]
