# Generated by Django 3.1.1 on 2020-11-05 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialidad', '0002_auto_20201029_2037'),
        ('especialidad', '0003_auto_20201103_1648'),
    ]

    operations = [
    ]
