# Generated by Django 3.1.2 on 2020-10-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20201024_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interprete',
            name='avatar',
            field=models.ImageField(default='avatars/no-img.jpg', upload_to='avatars/'),
        ),
    ]
