# Generated by Django 3.1.2 on 2020-11-03 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20201024_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interprete',
            name='calificacion',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='calificacion',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='saldo',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
