# Generated by Django 3.1.2 on 2020-11-03 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20201103_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interprete',
            name='dv',
            field=models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('^[0-9K]$')]),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='dv',
            field=models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('^[0-9K]$')]),
        ),
    ]
