# Generated by Django 3.1.1 on 2020-11-05 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20201029_2037'),
        ('usuario', '0005_auto_20201103_1648'),
    ]

    operations = [
    ]
