# Generated by Django 3.1.2 on 2020-11-05 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'reseña', 'verbose_name_plural': 'reseñas'},
        ),
    ]
