# Generated by Django 3.1.2 on 2020-10-29 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('especialidad', '0002_auto_20201029_2037'),
        ('usuario', '0004_auto_20201029_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_atencion', models.DateTimeField(blank=True)),
                ('fecha_termino', models.DateTimeField(blank=True)),
                ('estado', models.PositiveSmallIntegerField(choices=[(0, 'solicitado'), (1, 'atencion'), (2, 'finalizado')], default=0)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='atenciones', to='especialidad.especialidad')),
                ('interprete', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='atenciones', to='usuario.interprete')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='atenciones', to='usuario.solicitante')),
            ],
            options={
                'verbose_name_plural': 'Atenciones',
            },
        ),
    ]
