# Generated by Django 3.1.2 on 2020-11-05 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atencion',
            options={'verbose_name_plural': 'atenciones'},
        ),
    ]
