# Generated by Django 3.1.1 on 2020-11-05 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0002_auto_20201105_1601'),
        ('atencion', '0002_auto_20201105_1321'),
    ]

    operations = [
    ]
