# Generated by Django 3.1.2 on 2020-11-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0003_merge_20201105_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='fecha_atencion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='fecha_termino',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
