# Generated by Django 3.1.2 on 2020-11-05 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_auto_20201105_1601'),
        ('atencion', '0004_auto_20201105_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='interprete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='atenciones', to='usuario.interprete'),
        ),
    ]
