# Generated by Django 3.1.2 on 2020-11-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0005_auto_20201105_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencion',
            name='fecha_atencion',
        ),
        migrations.AddField(
            model_name='atencion',
            name='duracion',
            field=models.DecimalField(decimal_places=1, default=0.5, max_digits=3),
        ),
        migrations.AddField(
            model_name='atencion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='atencion',
            name='fecha_inicio_sesion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atencion',
            name='fecha_reserva',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(0, 'solicitado'), (1, 'aceptado'), (2, 'confirmado'), (3, 'sesion'), (4, 'finalizado')], default=0),
        ),
    ]
