# Generated by Django 3.1.2 on 2020-11-19 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0007_auto_20201119_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesion_id', models.IntegerField()),
                ('host_url', models.URLField(verbose_name='Link para iniciar')),
                ('join_url', models.URLField(verbose_name='Link para unirse')),
                ('atencion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sesion', to='atencion.atencion')),
            ],
        ),
    ]
